import { ERROR_CODE } from "../../core/errors.js";

// Only failures shared by all participating tools belong in this base.
export const COMMON_ERROR_CODE = {
  RATE_LIMITED: "RATE_LIMITED",
  FORBIDDEN: ERROR_CODE.FORBIDDEN,
  UPSTREAM_REJECTED: ERROR_CODE.UPSTREAM_REJECTED,
  UPSTREAM_UNAVAILABLE: ERROR_CODE.UPSTREAM_UNAVAILABLE,
  UPSTREAM_INVALID_RESPONSE: ERROR_CODE.UPSTREAM_INVALID_RESPONSE,
  INTERNAL_ERROR: ERROR_CODE.INTERNAL_ERROR,
} as const;

export const RESOURCE_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
  NOT_FOUND: ERROR_CODE.NOT_FOUND,
} as const;

export const PAGINATION_ERROR_CODE = {
  INVALID_CURSOR: "INVALID_CURSOR",
} as const;

// Shared by the currently approved writes with native approval and idempotency.
export const WRITE_ERROR_CODE = {
  ...RESOURCE_ERROR_CODE,
  APPROVAL_DECLINED: "APPROVAL_DECLINED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  UPSTREAM_OUTCOME_UNKNOWN: ERROR_CODE.UPSTREAM_OUTCOME_UNKNOWN,
} as const;
